-- AlterEnum
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'CASHAPP';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'APPLE_PAY';

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymentImage" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paymentNote" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerPaidAt" TIMESTAMP(3);
